<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modules\CompLib\CompLib.csproj" />
	<EmbeddedResource Include="data\shaderusages.txt" />
	<EmbeddedResource Include="data\shaderusages_legacy.txt" />
     <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
  </ItemGroup>
</Project>